/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    Carousel: typeof import("./src/components/Carousel.vue")["default"];
    CustomDialog: typeof import("./src/components/CustomDialog.vue")["default"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElOption: typeof import("element-plus/es")["ElOption"];
    ElSelect: typeof import("element-plus/es")["ElSelect"];
    HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"];
    NButton: typeof import("naive-ui")["NButton"];
    NCard: typeof import("naive-ui")["NCard"];
    NCarousel: typeof import("naive-ui")["NCarousel"];
    NCarouselItem: typeof import("naive-ui")["NCarouselItem"];
    NConfigProvider: typeof import("naive-ui")["NConfigProvider"];
    NGlobalStyle: typeof import("naive-ui")["NGlobalStyle"];
    NInput: typeof import("naive-ui")["NInput"];
    NInputGroup: typeof import("naive-ui")["NInputGroup"];
    NMessageProvider: typeof import("naive-ui")["NMessageProvider"];
    NModal: typeof import("naive-ui")["NModal"];
    NRadioButton: typeof import("naive-ui")["NRadioButton"];
    NRadioGroup: typeof import("naive-ui")["NRadioGroup"];
    NSpace: typeof import("naive-ui")["NSpace"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SearchInput: typeof import("./src/components/SearchInput.vue")["default"];
    Test: typeof import("./src/components/Test.vue")["default"];
  }
}
